<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="TEST_MAIN" Id="{e0fe771e-7548-4546-bb6c-2059f20a9739}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TEST_MAIN
VAR
  test_event: TestEvent;
  test_ads_logger: TestADSLogger;
  test_csv_logger: TestCSVLogger;
  test_utils: TestUtils;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();
TEST_STRING_CYCLE_TIME();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>